---
- name: install elasticsearch key
  rpm_key: key=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  when: ansible_os_family == 'RedHat'

- name: install elasticsearch repo
  template: src=elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644

- name: install elasticsearch dependencies
  yum: name={{ item }} state=installed
  with_items:
    - java-1.7.0-openjdk

- name: install elasticsearch
  yum: name=elasticsearch state=installed

- name: configure elasticsearch
  template: src="{{ item }}.j2" dest="/etc/elasticsearch/{{ item }}"
  with_items:
    - elasticsearch.yml
    - logging.yml
  notify: restart elasticsearch

- name: ensure elasticsearch is running
  service: name=elasticsearch state=started enabled=yes
